repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: name-tests-test
    -   id: end-of-file-fixer
        exclude: .*\.log
    -   id: trailing-whitespace
        exclude: .*\.log
    # -   id: pretty-format-json
    #     args: ['--autofix']
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.1
    hooks:
    -   id: clang-format
        types_or: [c++, c, cuda]
        args: ['-style={BasedOnStyle: Google}']
