import os
from pathlib import Path
from sys import get_coroutine_origin_tracking_depth
from tkinter import Image
import numpy as np
import logging
import json

from blokboi import Game
from src.image_gen import ImageGen

filetypes = ["json", "npy", "png"]


class MapLoader:
    def __init__(self, datapath=Path("data")):
        self.logger = logging.getLogger("blokboi.mapLoader")
        self.datapath = datapath

    def filetypes() -> list:
        """
        Get the filetypes generated by saving.

        ### Returns:
        `list`
        """
        return filetypes

    def load(self, map_key: int) -> tuple:
        """
        Load a map with the map key.

        ### Parameters
        `map_key : int`:
            the map number key.

        ### Returns
        `tuple`
            (scene, objective, relationship, coordinates, ground truth)
        """
        map_key = int(map_key)
        self.logger.info(f"Loading map {map_key}.")
        with open(
            self.datapath / "scenes" / f"scene_{map_key:05d}.npy", "rb"
        ) as npyfile:
            scene = np.load(npyfile)
        with open(
            self.datapath / "objectives" / f"objective_{map_key:05d}.json", "r"
        ) as jsonfile:
            objective = json.load(jsonfile)
        return (
            scene,
            objective["objective"],
            objective["relationship"],
            objective["coordinates"],
            objective["features"],
            objective["ground truth"],
        )

    def loadm(self, map_key: int) -> tuple:
        """
        Load a mechanically-generated map with the map key.

        ### Parameters
        `map_key : int`:
            the map number key.

        ### Returns
        `tuple`
            (scene, objective, relationship, coordinates, ground truth)
        """
        self.logger.info(f"Loading map {map_key}.")
        with open(
            self.datapath / "mechanical" / "scenes" / f"scene_{map_key:05d}.npy", "rb"
        ) as npyfile:
            scene = np.load(npyfile)
        with open(
            self.datapath
            / "mechanical"
            / "objectives"
            / f"objective_{map_key:05d}.json",
            "r",
        ) as jsonfile:
            objective = json.load(jsonfile)
        return (
            scene,
            objective["objective"],
            objective["relationship"],
            objective["coordinates"],
            objective["features"],
            objective["ground truth"],
        )

    def loadn(self, map_name: str) -> tuple:
        """
        Load a map by name.

        ### Parameters
        `map_name : str`:
            the map name.

        ### Returns
        `tuple`
            (scene, objective, relationship, coordinates, ground truth)
        """
        self.logger.info(f"Loading map {map_name}.")

        scenenum = -1
        found = False
        paths = Path(self.datapath / "toy").glob("**/*.json")
        for filepath in paths:
            with open(filepath, "r") as jsonfile:
                obj_dict = json.load(jsonfile)
                if obj_dict["id"] == map_name:
                    objective = obj_dict
                    scenenum = int(filepath.stem.split("_")[1])
                    with open(
                        self.datapath / "toy/scenes" / f"scene_{scenenum:05d}.npy", "rb"
                    ) as npyfile:
                        scene = np.load(npyfile)
                    found = True
                    break
            scenenum += 1
        if not found:
            self.logger.error(f"Could not find map named {map_name}.")
            print("Could not find map.")
            exit()

        return (
            scene,
            objective["objective"],
            objective["relationship"],
            objective["coordinates"],
            objective["features"],
            objective["ground truth"],
        )

    def list(self) -> str:
        """
        List the available maps.

        ### Returns
        `str`
        """
        self.logger.debug("Listing available maps.")
        available = []

        paths = Path(self.datapath / "toy").glob("**/*.json")
        for filepath in paths:
            with open(filepath, "r") as jsonfile:
                obj_dict = json.load(jsonfile)
                available.append(obj_dict["id"])
        return available

    def save(
        self, game_instance: Game, ground_truth: str = None, id: str = None
    ) -> None:
        """
        Save the intial state of a blokboi game.

        ### Parameters
        `game_instance : Game`:
            A blokboi game

        ### Returns
        nothing
        """
        self.logger.info("Saving scene.")

        jsondir = self.datapath / "objectives"
        npydir = self.datapath / "scenes"
        imgdir = self.datapath / "images"

        if not os.path.exists(jsondir):
            os.makedirs(jsondir)
        if not os.path.exists(npydir):
            os.makedirs(npydir)
        if not os.path.exists(imgdir):
            os.makedirs(imgdir)

        existing = [
            int(name.split(".")[0].split("_")[1])
            for name in os.listdir(jsondir)
            if Path.is_file(jsondir / name)
        ]
        if len(existing) == 0:
            newnum = 0
        else:
            newnum = max(existing) + 1

        scene = np.array(game_instance.init_data())

        objective = {}
        objective["objective"] = game_instance.objective()
        objective["relationship"] = game_instance.relationship()
        objective["coordinates"] = game_instance.init_coords()
        objective["features"] = game_instance.feature_mask()
        if ground_truth is not None:
            objective["ground truth"] = ground_truth
        else:
            objective["ground truth"] = game_instance.steps_taken()
        if id is not None:
            objective["id"] = id
        else:
            objective["id"] = newnum

        with open(jsondir / f"objective_{newnum:05d}.json", "w") as jsonfile, open(
            npydir / f"scene_{newnum:05d}.npy", "wb"
        ) as npyfile:
            json.dump(objective, jsonfile)
            np.save(npyfile, scene)
        ImageGen.make_image_from_str(
            game_instance.init_data(), imgdir / f"image_{newnum:05d}.png"
        )
