on:
  push:
    paths:
      - '**.cpp'
      - '**.cxx'
      - '**.c'
name: clang-format Code Formatter
jobs:
  lint:
    name: clang-format Code Formatter
    runs-on: ubuntu-latest
    steps:
    - name: Clang Code Formatter
      uses: ivanludvig/clang-format-action@v1.4
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
