name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3
      ## TODO: REMOVE WHEN MAKING PUBLIC REPO
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
